name: Code Checks
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting!
        run: echo hello world

  test-python-versions:
    name: Check Python ${{ matrix.python-version }} on Ubuntu
    runs-on: ${{ matrix.os-type }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10","3.11"]
	os-type: ["ubuntu-latest","windows-latest","macos-latest"]
        allow_failure: [false]
        include:
          - python-version: "3.12"
            allow_failure: true
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Python ${{ matrix.python-version  }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version  }}

      - name: Install package
        run: python -m pip install -e .[test]

      - name: Test package
        run: python -m pytest
